# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

added_files = [
    ('ui/dist', 'ui/dist'),
]

hidden_imports = [
    'uvicorn',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.http.httptools_impl',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespans',
    'uvicorn.lifespans.on',
    'uvicorn.lifespans.off',
    'anyio',
    'anyio._backends',
    'anyio._backends._asyncio',
    'fastapi',
    'starlette',
    'starlette.staticfiles',
    'httpx',
    'dotenv',
    'sqlite3',
    'pydantic',
    'pydantic_core',
    'app.main',
    'app.api.routes',
    'app.api.anthropic_routes',
    'app.api.accounts_routes',
    'app.api.stats_routes',
    'app.api.settings_routes',
    'app.api.keys_routes',
    'app.api.mcp_routes',
    'app.api.image_routes',
    'app.api.audio_routes',
    'app.api.system_routes',
    'app.core.account_store',
    'app.core.agy_http_client',
    'app.core.agy_runner',
    'app.core.auto_classifier',
    'app.core.cloudcode_common',
    'app.core.cloudcode_lifecycle',
    'app.core.db',
    'app.core.paths',
    'app.core.http_tools_bridge',
    'app.core.key_manager',
    'app.core.logging_setup',
    'app.core.model_manager',
    'app.core.oauth_refresh',
    'app.core.pool_git_sync',
    'app.core.pool_manager',
    'app.core.proxy_config',
    'app.core.request_tracer',
    'app.core.security',
    'app.core.stats_store',
]

a = Analysis(
    ['entrypoint.py'],
    pathex=['.'],
    binaries=[],
    datas=added_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'scipy', 'pandas', 'IPython', 'notebook', 'pytest'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

icon_file = 'app.ico' if sys.platform.startswith('win') and os.path.exists('app.ico') else None

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='agy2api',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_file,
)
